""" add color field to categories

Revision ID: 19d71844e69a
Revises: 57b799a8f4d0
Create Date: 2026-05-15 12:43:12.817223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19d71844e69a'
down_revision: Union[str, Sequence[str], None] = '57b799a8f4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('color', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('date_of_transaction', sa.Date(), nullable=True))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('transactions', 'date_of_transaction')
    op.drop_column('categories', 'color')
    # ### end Alembic commands ###
